### ISSUE TITLE
Sample of video interpolation

### ISSUE THREAD

**Issue by semel1** [jhogsett/EMA-VFI-WebUI#125]
Here the sample of video you suggested,  interpolated to  768fps using RIFE.
https://youtu.be/mFU8z-DSTds

**Comment by jhogsett** [comment]
Thank you. That looks pretty good. I'm noticing a significant loss of detail - especially noticeable if you compare the section of the videos -- both VFIformer and EMA VFI do a better job maintaining the car grill detail compared to your example, with EMA VFI doing the best of the three.

My understanding is EMA VFI is based in part on RIFE so I may be already reaping the benefits.
