### ISSUE TITLE
please do portable with own venv, im tired of all the repos havin issues with dependencies and outdated commands...

### ISSUE THREAD

**Issue by 2blackbar** [jhogsett/EMA-VFI-WebUI#150]
(myenv) F:\frame interEMA>python interpolate.py
Traceback (most recent call last):
  File "interpolate.py", line 12, in <module>
    from webui_utils.simple_utils import sortable_float_index
  File "F:\frame interEMA\webui_utils\simple_utils.py", line 97, in <module>
    mantissa_width : float | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by jhogsett** [comment]
@2blackbar Thank you! It's been on the TODO list for some time to make a simple installer.
- If you use `Python 3.10.9` you'll avoid this particular problem
    - Another user ran into this issue and this solved it for them
- It's straightforward to set up a new Anaconda environment with a specific Python version
    - https://numdifftools.readthedocs.io/en/stable/how-to/create_virtual_env_with_conda.html
