### ISSUE TITLE
Made one click installer for it

### ISSUE THREAD

**Issue by 2blackbar** [jhogsett/EMA-VFI-WebUI#151]
Hey man, i did installer for it its for your  webui  , it creates own venv in folder and then you can just run webui to activate venv and have fun in webui, i have one issue i see, i can interpolate just one frame inbetwee, with more frames it just takes forever , there is no progressbar so i have no clue whats happening .
Ok finally it did interpolate 7 frames in webui but its so slow its like snail speed compred to rife which is very fast... is that normal ?

feel free to include it no credit
Contents

@echo off

REM Create the virtual environment
python -m venv venv

REM Activate the virtual environment
call venv\Scripts\activate.bat

REM Install dependencies
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121
pip install -U scikit-image
pip install numpy
pip install opencv-python
pip install timm
pip install tqdm
pip install gradio
pip install basicsr
pip install realesrgan

echo Virtual environment set up and dependencies installed!

REM Ask if the user wants to run the webui.py script
set /p run_webui="Do you want to run the webui.py script (Y/N)? "
if /i "%run_webui%"=="Y" (
python webui.py
)

pause

[EMA-VFI-WebUI install.zip](https://github.com/jhogsett/EMA-VFI-WebUI/files/12429880/EMA-VFI-WebUI.install.zip)

**Comment by jhogsett** [comment]
@2blackbar thanks I'll check it out. I noticed a couple things
- I don't see it installing EMA-VFI, nor copying the required folders/model to the EMA-VFI WebUI folder
- I see it installing realesrgan, but not copying the required folders/model to the EMA-VFI WebUI folder
- An ideal install script could also install the recommended versions of Python and Venv, and also FFmpeg

> it just takes forever , 
I am calling into the EMA-VFI code to do the interpolation. I have no control over what happens there and the timing. I can suggest:
- Check if your GPU is being used and is appropriate for the EMA-VFI engine according to their recommendations (generally NVIDIA recent hardward)
- Compare to the inference example provided by the EMA-VFI engine developers. That will give you a reading on whether my tool is working slower.

> there is no progressbar so i have no clue whats happening .
- The progress bars are shown in the console

**Comment by 2blackbar** [comment]
Yeah you download or clone repo yourself, this is just to run dependencies with no tinkering around and detecrive work
