### ISSUE TITLE
Can You add RIFE support?

### ISSUE THREAD

**Issue by 2blackbar** [jhogsett/EMA-VFI-WebUI#152]
Its much faster
https://github.com/nihui/rife-ncnn-vulkan

**Comment by jhogsett** [comment]
Thank you. On the long term plan is to switch to a _wrapper_ model and support other interpolation engines.

**Comment by 2blackbar** [comment]
That would be nice cause it really takes ages and you made some nice tools that would be great for RIFE
Its there a fast way to use Rife instead of current one ? For rife i just run exe file with python tkinter gui and its commandline arguments but what you did is a lot better
