### ISSUE TITLE
How can I process video files directly,not picture sequence frame

### ISSUE THREAD

**Issue by zhanghongyong123456** [jhogsett/EMA-VFI-WebUI#221]
Why can not input video directly for interpolation processing, only the image sequence file can be operated?
![image](https://github.com/jhogsett/EMA-VFI-WebUI/assets/48466610/ea7a0a66-b714-480a-80d2-e3e950066731)

**Comment by jhogsett** [comment]
@zhanghongyong123456 
> Why can not input video directly for interpolation processing, only the image sequence file can be operated? ![image](https://user-images.githubusercontent.com/48466610/285420755-ea7a0a66-b714-480a-80d2-e3e950066731.png)

Try the _Video Remixer_ tab. It's designed for starting initially with a video (optionally + audio) and applying various processing, including Video Inflation.

The software uses PNG files internally to handle video losslessly. The tools in the other tabs are designed to operate on these sets of PNG files. 

Also, visit the Tools tab, and in particular, the File Conversion tab. There are tools to convert between video and PNG formats.

**Comment by zhanghongyong123456** [comment]
> @zhanghongyong123456
> 
> > Why can not input video directly for interpolation processing, only the image sequence file can be operated? ![image](https://user-images.githubusercontent.com/48466610/285420755-ea7a0a66-b714-480a-80d2-e3e950066731.png)
> 
> Try the _Video Remixer_ tab. It's designed for starting initially with a video (optionally + audio) and applying various processing, including Video Inflation.
> 
> The software uses PNG files internally to handle video losslessly. The tools in the other tabs are designed to operate on these sets of PNG files.
> 
> Also, visit the Tools tab, and in particular, the File Conversion tab. There are tools to convert between video and PNG formats.
when   i  use  interpolate   video   get    image sequence,how  to  conbine   use  tool  tab (PNG Sequence to MP4) 
![image](https://github.com/jhogsett/EMA-VFI-WebUI/assets/48466610/ff615458-42bf-490d-8f10-6db757d3bc1e)
![image](https://github.com/jhogsett/EMA-VFI-WebUI/assets/48466610/58267bd9-38d0-4f7a-b9b0-42d7ffa072ba)

**Comment by jhogsett** [comment]
@zhanghongyong123456 I'm sorry you got this error. It's easy to work around. It is because FFmpeg requires files to be named with sequential index numbers. However the Video Inflation feature intentionally does not automatically re-index the files, given the existing names can be used to determine which original frame the interpolated frames were made from.

To Fix: use the Tools -> Resequence Files feature. It will get the list of files, then re-index them properly. Then PNGtoMP4 can be used without further issue.

I recommend using the Video Remixer tab, which is designed to integrate all the low-level workings together in a smooth experience.

**Comment by zhanghongyong123456** [comment]
> @zhanghongyong123456 I'm sorry you got this error. It's easy to work around. It is because FFmpeg requires files to be named with sequential index numbers. However the Video Inflation feature intentionally does not automatically re-index the files, given the existing names can be used to determine which original frame the interpolated frames were made from.
> 
> To Fix: use the Tools -> Resequence Files feature. It will get the list of files, then re-index them properly. Then PNGtoMP4 can be used without further issue.
> 
> I recommend using the Video Remixer tab, which is designed to integrate all the low-level workings together in a smooth experience.

thanks,i  try it ,
I found that the original project two scripts(demo_2x.py and  demo_Nx.py) used different models(['ours', 'ours_small'] and ['ours_t', 'ours_small_t'] ),Whether 2x or Nx this project is implemented on only one model(ours)

**Comment by jhogsett** [comment]
Thanks @zhanghongyong123456 

If you look in `config.yaml` there is a section that allows you to configure which model is used by EMA-VFI as follows:

```yaml
engine_settings:
  gpu_ids: "0"
  model: "ours"
  use_time_step: False
```

**Comment by jhogsett** [comment]
Note: When 

```yaml
use_time_step: true
```

It automatically added the "_t" to the model name that it will select and use. I have found that the time-step version of the model doesn't suit my needs, but I allow it to be enabled in the software.

**Comment by zhanghongyong123456** [comment]
> Note: When
> 
> ```yaml
> use_time_step: true
> ```
> 
> It automatically added the "_t" to the model name that it will select and use. I have found that the time-step version of the model doesn't suit my needs, but I allow it to be enabled in the software.

Thanks for the answer, what is the difference between several models

**Comment by jhogsett** [comment]
> Thanks for the answer, what is the difference between several models

My understanding is the main model "ours" is strictly for 50% interpolation between two frames, and the time-step version "ours_t" allows interpolation at any percentage between two frames. Also there are small versions of the models as well, which I don't use.

I found the time-step model to be insufficient compared to my binary-search (Frame Search feature) method of achieving interpolation at other than the 50% point.

I recommend reaching out to the EMA-VFI folks directly for a more precise technical answer.

**Comment by zhanghongyong123456** [comment]
> > Thanks for the answer, what is the difference between several models
> 
> My understanding is the main model "ours" is strictly for 50% interpolation between two frames, and the time-step version "ours_t" allows interpolation at any percentage between two frames. Also there are small versions of the models as well, which I don't use.
> 
> I found the time-step model to be insufficient compared to my binary-search (Frame Search feature) method of achieving interpolation at other than the 50% point.
> 
> I recommend reaching out to the EMA-VFI folks directly for a more precise technical answer.

Thank you very much for your clarification,
