### ISSUE TITLE
fixed error  ModuleNotFoundError: No module named 'Trainer'

### ISSUE THREAD

**Issue by tehMArs** [jhogsett/EMA-VFI-WebUI#333]
webui.py", line 9, in <module>
    from interpolate_engine import InterpolateEngine
  File "EMA-VFI-WebUI\interpolate_engine.py", line 7, in <module>
    from Trainer import Model # pylint: disable=import-error
ModuleNotFoundError: No module named 'Trainer'

in EMA-VFI-WebUI\EMA-VFI-WebUI rename Trainer.py trainer.py and 
\EMA-VFI-WebUI\EMA-VFI-WebUI\interpolate_engine.py change from Trainer import Model to from trainer import Model

**Comment by jhogsett** [comment]
@tehMArs Thanks! Can you please submit a pull request?
