### ISSUE TITLE
Process more than 2 frames?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [jhogsett/EMA-VFI-WebUI#4]
Thanks for sharing this great work!   Is there an easy to process an entire video with this yet, or are we limited to using a pair of input frames only?

**Comment by jhogsett** [comment]
Hi @noobtoob4lyfe there are a few features that will interpolate across a series of frames:

Video Inflation: inserts _filler_ frames between all frame pairs to create slow motion, or smooth low-FPS footage
Resynthesize Video: creates new middle frames for all frame _triplets_, creating a whole new set of frames for use in restoration
Upscale Frames: creates a set of cleaned and/or upsized frames
Change FPS: use interpolation to create frames to convert any FPS to any other FPS
Various tools that will process sets of PNG frame files, for instance, to create a .MP4 video

Let me know what you would like to accomplish with the tool and I can provide more a more detailed workflow.
