### ISSUE TITLE
Usage with Old B&W Movies

### ISSUE THREAD

**Issue by oatsvine** [jhogsett/EMA-VFI-WebUI#78]
Is it worth experimenting with this framework to restore (reduce grain, stabilize frames, increase frame rate, etc) copies of black and white movies (e.g. 1930s motion pictures)?

**Comment by jhogsett** [comment]
@oatsvine I would recommend it, yes:
* The _Resynthesize Video_ feature is especially good at both reducing grain/noise and stabilizing frames
    * Each frame is interpolated from scratch using the adjacent frames
    * This gets rid of noise that had been present in the frame, and noise not common to both adjacent frames
    * See an example here: (YouTube) https://youtube.com/shorts/lKtY2CHqA98 (top is original footage, bottom is resynthesized) * The _Video Inflation_ feature can be used to interpolate new frames to increase frame rate. It works well on most content, including B&W content.
    * See an example here: (32X frame expansion, YouTube) https://youtu.be/rOiALIN805w

**Comment by oatsvine** [comment]
Thanks for the guidance! I'll give this a shot and report back. Do you have a Dockerfile setup handy by chance?

**Comment by jhogsett** [comment]
YW, I don't have a Dockerfile, but that seems like a good idea so I'll add it to my todo list. Thanks!

Speaking of restoring B&W content, a project I'll be working on soon is restoring some old "Peter Gunn" episodes I've been recording over the air from MeTV.
