### ISSUE TITLE
Could you integrate video frame extraction?

### ISSUE THREAD

**Issue by zelenooki87** [jhogsett/EMA-VFI-WebUI#87]
Please integrate ffmpeg video extraction and option to save intepolated frames as video.
That will save my time very.
thank you

**Comment by jhogsett** [comment]
Hi @zelenooki87 both features are already available:

MP4 to PNG Sequence
- https://github.com/jhogsett/EMA-VFI-WebUI/wiki/MP4-to-PNG-Sequence
- rip a .MP4 video into a PNG frame sequence

PNG Sequence to MP4
- https://github.com/jhogsett/EMA-VFI-WebUI/wiki/PNG-Sequence-to-MP4
- Convert a PNG frame sequence to a .MP4 video

There are some other tools available on the Tools tab
- https://github.com/jhogsett/EMA-VFI-WebUI/wiki/Tools
-

**Comment by zelenooki87** [comment]
yeah, I knew that.
Would you consider to automate process....?
just to insert video file and than convert to desired framerate, like nmkd did in Flowframes?
and add prores option as export. With audio. 
Project is okay, ema vfi has great potential but please automate process for simpliffier use.
thanks

**Comment by jhogsett** [comment]
I see. I think it would work like this:
- submit a video file
- choose some processing options like AI frame interpolation and AI frame upscaling
- automatically handle the processing and produce a final video, including audio
- All done with a few clicks and one button click

I like it.

I'm working on something like this called _Video Remixer_ (in final testing stage). It works like this:
- Submit a video
- choose some options (aspect ratio correction, split in scenes by: detected scene, detected break or by each minute
- automatically makes thumbnails of each scene 
- has a _Scene Chooser_ to choose which scenes to keep vs. leave out
- After choosing scenes, provides processing choices (interpolation, upscaling, etc.)
- Processes the frames and recombines the original audio
- Produces a final video w/audio of the selected scenes stitched together

If ones leaves out the _scene choosing_ part of the feature, it's almost exactly what you're asking for. (I don't know much about prores, but if FFmpeg can output it, so can this tool.)

I plan to merge the [pull request](https://github.com/jhogsett/EMA-VFI-WebUI/pull/86) soon. The feature tab will be found on Tools, Split & Merge Frames, Video Remixer.

**Comment by zelenooki87** [comment]
How should I set new video path on video remixer tab?
always getting error,
frame interpolation on extracted folders working okay, but when I try to create new project, it wont let me says "error"

**Comment by jhogsett** [comment]
It should be a full path to a video on the same server, like (in my case):

`c:\content\videos\somevideo.mp4`

What is the error? What is showing in the log viewer?

**Comment by zelenooki87** [comment]
friend, problem in my case was environment conda, cause I used it for onother two github projects... i created new conda environment from scratch and everything is OK.

**Comment by zelenooki87** [comment]
could you please change factor for saving videos to be smaller than 17? for lossless saving? thank you

**Comment by jhogsett** [comment]
You can alter that default value yourself in the `config.yaml` file, it's in the 'remixer_settings' section:

```
remixer_settings:
  minimum_crf: 17
```

Also, if you care to, you can save custom settings to your own .yaml file and pass it on the command line when starting up. 

This is how I start mine:

```
>python webui.py --config_path "config-local.yaml"
```

**Comment by zelenooki87** [comment]
Thank you, realy appreciate

**Comment by jhogsett** [comment]
@zelenooki87 you might find this feature useful https://github.com/jhogsett/EMA-VFI-WebUI/pull/97

It let's you output the remixed video with your own custom audio and video FFmpeg command-line options, so you are not limited to only MP4. I think this might help you, since you mentioned prores output. I have tested and been able to create MPG and WMV videos using it.
